namespace we {
  export namespace di {
    export const BETFIELD_IMAGE_MAPPING = {
      ODD: 'd_di_betboard_hover_large_group_png',
      EVEN: 'd_di_betboard_hover_large_group_png',
      BIG: 'd_di_betboard_hover_large_group_png',
      SMALL: 'd_di_betboard_hover_large_group_png',
      SUM_4: 'd_di_betboard_hover_sum_png',
      SUM_5: 'd_di_betboard_hover_sum_png',
      SUM_6: 'd_di_betboard_hover_sum_png',
      SUM_7: 'd_di_betboard_hover_sum_png',
      SUM_8: 'd_di_betboard_hover_sum_png',
      SUM_9: 'd_di_betboard_hover_sum_png',
      SUM_10: 'd_di_betboard_hover_sum_png',
      SUM_11: 'd_di_betboard_hover_sum_png',
      SUM_12: 'd_di_betboard_hover_sum_png',
      SUM_13: 'd_di_betboard_hover_sum_png',
      SUM_14: 'd_di_betboard_hover_sum_png',
      SUM_15: 'd_di_betboard_hover_sum_png',
      SUM_16: 'd_di_betboard_hover_sum_png',
      SUM_17: 'd_di_betboard_hover_sum_png',
      TRIPLE_1: 'd_di_betboard_hover_triple_png',
      TRIPLE_2: 'd_di_betboard_hover_triple_png',
      TRIPLE_3: 'd_di_betboard_hover_triple_png',
      TRIPLE_4: 'd_di_betboard_hover_triple_png',
      TRIPLE_5: 'd_di_betboard_hover_triple_png',
      TRIPLE_6: 'd_di_betboard_hover_triple_png',
      TRIPLE_ALL: 'd_di_betboard_hover_triple_all_png',
      DOUBLE_1: 'd_di_betboard_hover_double_png',
      DOUBLE_2: 'd_di_betboard_hover_double_png',
      DOUBLE_3: 'd_di_betboard_hover_double_png',
      DOUBLE_4: 'd_di_betboard_hover_double_png',
      DOUBLE_5: 'd_di_betboard_hover_double_png',
      DOUBLE_6: 'd_di_betboard_hover_double_png',
      COMBINE_1_2: 'd_di_betboard_hover_combine_png',
      COMBINE_1_3: 'd_di_betboard_hover_combine_png',
      COMBINE_1_4: 'd_di_betboard_hover_combine_png',
      COMBINE_1_5: 'd_di_betboard_hover_combine_png',
      COMBINE_1_6: 'd_di_betboard_hover_combine_png',
      COMBINE_2_3: 'd_di_betboard_hover_combine_png',
      COMBINE_2_4: 'd_di_betboard_hover_combine_png',
      COMBINE_2_5: 'd_di_betboard_hover_combine_png',
      COMBINE_2_6: 'd_di_betboard_hover_combine_png',
      COMBINE_3_4: 'd_di_betboard_hover_combine_png',
      COMBINE_3_5: 'd_di_betboard_hover_combine_png',
      COMBINE_3_6: 'd_di_betboard_hover_combine_png',
      COMBINE_4_5: 'd_di_betboard_hover_combine_png',
      COMBINE_4_6: 'd_di_betboard_hover_combine_png',
      COMBINE_5_6: 'd_di_betboard_hover_combine_png',
      SPECIFIC_1: 'd_di_betboard_hover_specific_png',
      SPECIFIC_2: 'd_di_betboard_hover_specific_png',
      SPECIFIC_3: 'd_di_betboard_hover_specific_png',
      SPECIFIC_4: 'd_di_betboard_hover_specific_png',
      SPECIFIC_5: 'd_di_betboard_hover_specific_png',
      SPECIFIC_6: 'd_di_betboard_hover_specific_png',
    };
  }
}
