namespace we {
  export namespace di {
    export enum WinType {
      NONE,
      DRAGON,
      TIGER,
      TIE,
    }

    export const BetField = {
      ODD: 'ODD',
      EVEN: 'EVEN',
      BIG: 'BIG',
      SMALL: 'SMALL',
      SUM_4:  'SUM_4',
      SUM_5: 'SUM_5',
      SUM_6: 'SUM_6',
      SUM_7: 'SUM_7',
      SUM_8: 'SUM_8',
      SUM_9: 'SUM_9',
      SUM_10: 'SUM_10',
      SUM_11: 'SUM_11',
      SUM_12: 'SUM_12',
      SUM_13: 'SUM_13',
      SUM_14: 'SUM_14',
      SUM_15: 'SUM_15',
      SUM_16: 'SUM_16',
      SUM_17: 'SUM_17',
      TRIPLE_1: 'TRIPLE_1',
      TRIPLE_2: 'TRIPLE_2',
      TRIPLE_3: 'TRIPLE_3',
      TRIPLE_4: 'TRIPLE_4',
      TRIPLE_5: 'TRIPLE_5',
      TRIPLE_6: 'TRIPLE_6',
      TRIPLE_ALL: 'TRIPLE_ALL',
      DOUBLE_1: 'DOUBLE_1',
      DOUBLE_2: 'DOUBLE_2',
      DOUBLE_3: 'DOUBLE_3',
      DOUBLE_4: 'DOUBLE_4',
      DOUBLE_5: 'DOUBLE_5',
      DOUBLE_6: 'DOUBLE_6',
      COMBINE_1_2: 'COMBINE_1_2',
      COMBINE_1_3: 'COMBINE_1_3',
      COMBINE_1_4: 'COMBINE_1_4',
      COMBINE_1_5: 'COMBINE_1_5',
      COMBINE_1_6: 'COMBINE_1_6',
      COMBINE_2_3: 'COMBINE_2_3',
      COMBINE_2_4: 'COMBINE_2_4',
      COMBINE_2_5: 'COMBINE_2_5',
      COMBINE_2_6: 'COMBINE_2_6',
      COMBINE_3_4: 'COMBINE_3_4',
      COMBINE_3_5: 'COMBINE_3_5',
      COMBINE_3_6: 'COMBINE_3_6',
      COMBINE_4_5: 'COMBINE_4_5',
      COMBINE_4_6: 'COMBINE_4_6',
      COMBINE_5_6: 'COMBINE_5_6',
      SPECIFIC_1: 'SPECIFIC_1',
      SPECIFIC_2: 'SPECIFIC_2',
      SPECIFIC_3: 'SPECIFIC_3',
      SPECIFIC_4: 'SPECIFIC_4',
      SPECIFIC_5: 'SPECIFIC_5',
      SPECIFIC_6: 'SPECIFIC_6',
    };
  }
}
