namespace enums {
  export const event = {
    baccarat: {
      CLICK_CHIP: 'CLICK_CHIP',
    },

    event: {
      CONNECT_SUCCESS: 'MQTT_EV_CONNECT_SUCCESS',
      CONNECT_FAIL: 'MQTT_EV_CONNECT_FAIL',
      PLAYER_PROFILE_UPDATE: 'PLAYER_PROFILE_UPDATE',
      TABLE_LIST_UPDATE: 'TABLE_LIST_UPDATE',
      TABLE_INFO_UPDATE: 'TABLE_INFO_UPDATE',
      BALANCE_UPDATE: 'BALANCE_UPDATE',
      BET_TABLE_LIST_UPDATE: 'BET_TABLE_LIST_UPDATE',
    },
  };
}
