namespace enums {
  export const event = {
    baccarat: {
      CLICK_CHIP: 'CLICK_CHIP',
    },

    event: {
      CONNECT_SUCCESS: 'MQTT_EV_CONNECT_SUCCESS',
      CONNECT_FAIL: 'MQTT_EV_CONNECT_FAIL',
      PLAYER_PROFILE_UPDATE: 'PLAYER_PROFILE_UPDATE',
      TABLE_LIST_UPDATE: 'TABLE_LIST_UPDATE',
      TABLE_INFO_UPDATE: 'TABLE_INFO_UPDATE',
      PLAYER_BET_INFO_UPDATE: 'PLAYER_BET_INFO_UPDATE',
      BALANCE_UPDATE: 'BALANCE_UPDATE',
      ROADMAP_UPDATE: 'ROADMAP_UPDATE',

      INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
      EXCEED_BET_LIMIT: 'EXCEED_BET_LIMIT',
    },
  };
}
