namespace we {
  export namespace ro {
    export class ChipLayer extends we.ui.ChipLayer {
      // group
      protected _direct_0_group: eui.Group;
      protected _direct_1_group: eui.Group;
      protected _direct_2_group: eui.Group;
      protected _direct_3_group: eui.Group;
      protected _direct_4_group: eui.Group;
      protected _direct_5_group: eui.Group;
      protected _direct_6_group: eui.Group;
      protected _direct_7_group: eui.Group;
      protected _direct_8_group: eui.Group;
      protected _direct_9_group: eui.Group;
      protected _direct_10_group: eui.Group;
      protected _direct_11_group: eui.Group;
      protected _direct_12_group: eui.Group;
      protected _direct_13_group: eui.Group;
      protected _direct_14_group: eui.Group;
      protected _direct_15_group: eui.Group;
      protected _direct_16_group: eui.Group;
      protected _direct_17_group: eui.Group;
      protected _direct_18_group: eui.Group;
      protected _direct_19_group: eui.Group;
      protected _direct_20_group: eui.Group;
      protected _direct_21_group: eui.Group;
      protected _direct_22_group: eui.Group;
      protected _direct_23_group: eui.Group;
      protected _direct_24_group: eui.Group;
      protected _direct_25_group: eui.Group;
      protected _direct_26_group: eui.Group;
      protected _direct_27_group: eui.Group;
      protected _direct_28_group: eui.Group;
      protected _direct_29_group: eui.Group;
      protected _direct_30_group: eui.Group;
      protected _direct_31_group: eui.Group;
      protected _direct_32_group: eui.Group;
      protected _direct_33_group: eui.Group;
      protected _direct_34_group: eui.Group;
      protected _direct_35_group: eui.Group;
      protected _direct_36_group: eui.Group;
      protected _separate_1_2_group: eui.Group;
      protected _separate_2_3_group: eui.Group;
      protected _separate_4_5_group: eui.Group;
      protected _separate_5_6_group: eui.Group;
      protected _separate_7_8_group: eui.Group;
      protected _separate_8_9_group: eui.Group;
      protected _separate_10_11_group: eui.Group;
      protected _separate_11_12_group: eui.Group;
      protected _separate_13_14_group: eui.Group;
      protected _separate_14_15_group: eui.Group;
      protected _separate_16_17_group: eui.Group;
      protected _separate_17_18_group: eui.Group;
      protected _separate_19_20_group: eui.Group;
      protected _separate_20_21_group: eui.Group;
      protected _separate_22_23_group: eui.Group;
      protected _separate_23_24_group: eui.Group;
      protected _separate_25_26_group: eui.Group;
      protected _separate_26_27_group: eui.Group;
      protected _separate_28_29_group: eui.Group;
      protected _separate_29_30_group: eui.Group;
      protected _separate_31_32_group: eui.Group;
      protected _separate_32_33_group: eui.Group;
      protected _separate_34_35_group: eui.Group;
      protected _separate_35_36_group: eui.Group;
      protected _separate_0_1_group: eui.Group;
      protected _separate_0_2_group: eui.Group;
      protected _separate_0_3_group: eui.Group;
      protected _separate_1_4_group: eui.Group;
      protected _separate_2_5_group: eui.Group;
      protected _separate_3_6_group: eui.Group;
      protected _separate_4_7_group: eui.Group;
      protected _separate_5_8_group: eui.Group;
      protected _separate_6_9_group: eui.Group;
      protected _separate_7_10_group: eui.Group;
      protected _separate_8_11_group: eui.Group;
      protected _separate_9_12_group: eui.Group;
      protected _separate_10_13_group: eui.Group;
      protected _separate_11_14_group: eui.Group;
      protected _separate_12_15_group: eui.Group;
      protected _separate_13_16_group: eui.Group;
      protected _separate_14_17_group: eui.Group;
      protected _separate_15_18_group: eui.Group;
      protected _separate_16_19_group: eui.Group;
      protected _separate_17_20_group: eui.Group;
      protected _separate_18_21_group: eui.Group;
      protected _separate_19_22_group: eui.Group;
      protected _separate_20_23_group: eui.Group;
      protected _separate_21_24_group: eui.Group;
      protected _separate_22_25_group: eui.Group;
      protected _separate_23_26_group: eui.Group;
      protected _separate_24_27_group: eui.Group;
      protected _separate_25_28_group: eui.Group;
      protected _separate_26_29_group: eui.Group;
      protected _separate_27_30_group: eui.Group;
      protected _separate_28_31_group: eui.Group;
      protected _separate_29_32_group: eui.Group;
      protected _separate_30_33_group: eui.Group;
      protected _separate_31_34_group: eui.Group;
      protected _separate_32_35_group: eui.Group;
      protected _separate_33_36_group: eui.Group;
      protected _street_1_2_3_group: eui.Group;
      protected _street_4_5_6_group: eui.Group;
      protected _street_7_8_9_group: eui.Group;
      protected _street_10_11_12_group: eui.Group;
      protected _street_13_14_15_group: eui.Group;
      protected _street_16_17_18_group: eui.Group;
      protected _street_19_20_21_group: eui.Group;
      protected _street_22_23_24_group: eui.Group;
      protected _street_25_26_27_group: eui.Group;
      protected _street_28_29_30_group: eui.Group;
      protected _street_31_32_33_group: eui.Group;
      protected _street_34_35_36_group: eui.Group;
      protected _street_0_1_2_group: eui.Group;
      protected _street_0_2_3_group: eui.Group;
      protected _corner_1_2_4_5_group: eui.Group;
      protected _corner_2_3_5_6_group: eui.Group;
      protected _corner_4_5_7_8_group: eui.Group;
      protected _corner_5_6_8_9_group: eui.Group;
      protected _corner_7_8_10_11_group: eui.Group;
      protected _corner_8_9_11_12_group: eui.Group;
      protected _corner_10_11_13_14_group: eui.Group;
      protected _corner_11_12_14_15_group: eui.Group;
      protected _corner_13_14_16_17_group: eui.Group;
      protected _corner_14_15_17_18_group: eui.Group;
      protected _corner_16_17_19_20_group: eui.Group;
      protected _corner_17_18_20_21_group: eui.Group;
      protected _corner_19_20_22_23_group: eui.Group;
      protected _corner_20_21_23_24_group: eui.Group;
      protected _corner_22_23_25_26_group: eui.Group;
      protected _corner_23_24_26_27_group: eui.Group;
      protected _corner_25_26_28_29_group: eui.Group;
      protected _corner_26_27_29_30_group: eui.Group;
      protected _corner_28_29_31_32_group: eui.Group;
      protected _corner_29_30_32_33_group: eui.Group;
      protected _corner_31_32_34_35_group: eui.Group;
      protected _corner_32_33_35_36_group: eui.Group;
      protected _corner_0_1_2_3_group: eui.Group;
      protected _line_1_6_group: eui.Group;
      protected _line_4_9_group: eui.Group;
      protected _line_7_12_group: eui.Group;
      protected _line_10_15_group: eui.Group;
      protected _line_13_18_group: eui.Group;
      protected _line_16_21_group: eui.Group;
      protected _line_19_24_group: eui.Group;
      protected _line_22_27_group: eui.Group;
      protected _line_25_30_group: eui.Group;
      protected _line_28_33_group: eui.Group;
      protected _line_31_36_group: eui.Group;
      protected _row_1_group: eui.Group;
      protected _row_2_group: eui.Group;
      protected _row_3_group: eui.Group;
      protected _dozen_1_12_group: eui.Group;
      protected _dozen_13_24_group: eui.Group;
      protected _dozen_25_36_group: eui.Group;
      protected _red_group: eui.Group;
      protected _black_group: eui.Group;
      protected _odd_group: eui.Group;
      protected _even_group: eui.Group;
      protected _small_group: eui.Group;
      protected _big_group: eui.Group;

      protected _direct_0_betChipStack: ro.BetChipStack;
      protected _direct_1_betChipStack: ro.BetChipStack;
      protected _direct_2_betChipStack: ro.BetChipStack;
      protected _direct_3_betChipStack: ro.BetChipStack;
      protected _direct_4_betChipStack: ro.BetChipStack;
      protected _direct_5_betChipStack: ro.BetChipStack;
      protected _direct_6_betChipStack: ro.BetChipStack;
      protected _direct_7_betChipStack: ro.BetChipStack;
      protected _direct_8_betChipStack: ro.BetChipStack;
      protected _direct_9_betChipStack: ro.BetChipStack;
      protected _direct_10_betChipStack: ro.BetChipStack;
      protected _direct_11_betChipStack: ro.BetChipStack;
      protected _direct_12_betChipStack: ro.BetChipStack;
      protected _direct_13_betChipStack: ro.BetChipStack;
      protected _direct_14_betChipStack: ro.BetChipStack;
      protected _direct_15_betChipStack: ro.BetChipStack;
      protected _direct_16_betChipStack: ro.BetChipStack;
      protected _direct_17_betChipStack: ro.BetChipStack;
      protected _direct_18_betChipStack: ro.BetChipStack;
      protected _direct_19_betChipStack: ro.BetChipStack;
      protected _direct_20_betChipStack: ro.BetChipStack;
      protected _direct_21_betChipStack: ro.BetChipStack;
      protected _direct_22_betChipStack: ro.BetChipStack;
      protected _direct_23_betChipStack: ro.BetChipStack;
      protected _direct_24_betChipStack: ro.BetChipStack;
      protected _direct_25_betChipStack: ro.BetChipStack;
      protected _direct_26_betChipStack: ro.BetChipStack;
      protected _direct_27_betChipStack: ro.BetChipStack;
      protected _direct_28_betChipStack: ro.BetChipStack;
      protected _direct_29_betChipStack: ro.BetChipStack;
      protected _direct_30_betChipStack: ro.BetChipStack;
      protected _direct_31_betChipStack: ro.BetChipStack;
      protected _direct_32_betChipStack: ro.BetChipStack;
      protected _direct_33_betChipStack: ro.BetChipStack;
      protected _direct_34_betChipStack: ro.BetChipStack;
      protected _direct_35_betChipStack: ro.BetChipStack;
      protected _direct_36_betChipStack: ro.BetChipStack;
      protected _separate_1_2_betChipStack: ro.BetChipStack;
      protected _separate_2_3_betChipStack: ro.BetChipStack;
      protected _separate_4_5_betChipStack: ro.BetChipStack;
      protected _separate_5_6_betChipStack: ro.BetChipStack;
      protected _separate_7_8_betChipStack: ro.BetChipStack;
      protected _separate_8_9_betChipStack: ro.BetChipStack;
      protected _separate_10_11_betChipStack: ro.BetChipStack;
      protected _separate_11_12_betChipStack: ro.BetChipStack;
      protected _separate_13_14_betChipStack: ro.BetChipStack;
      protected _separate_14_15_betChipStack: ro.BetChipStack;
      protected _separate_16_17_betChipStack: ro.BetChipStack;
      protected _separate_17_18_betChipStack: ro.BetChipStack;
      protected _separate_19_20_betChipStack: ro.BetChipStack;
      protected _separate_20_21_betChipStack: ro.BetChipStack;
      protected _separate_22_23_betChipStack: ro.BetChipStack;
      protected _separate_23_24_betChipStack: ro.BetChipStack;
      protected _separate_25_26_betChipStack: ro.BetChipStack;
      protected _separate_26_27_betChipStack: ro.BetChipStack;
      protected _separate_28_29_betChipStack: ro.BetChipStack;
      protected _separate_29_30_betChipStack: ro.BetChipStack;
      protected _separate_31_32_betChipStack: ro.BetChipStack;
      protected _separate_32_33_betChipStack: ro.BetChipStack;
      protected _separate_34_35_betChipStack: ro.BetChipStack;
      protected _separate_35_36_betChipStack: ro.BetChipStack;
      protected _separate_0_1_betChipStack: ro.BetChipStack;
      protected _separate_0_2_betChipStack: ro.BetChipStack;
      protected _separate_0_3_betChipStack: ro.BetChipStack;
      protected _separate_1_4_betChipStack: ro.BetChipStack;
      protected _separate_2_5_betChipStack: ro.BetChipStack;
      protected _separate_3_6_betChipStack: ro.BetChipStack;
      protected _separate_4_7_betChipStack: ro.BetChipStack;
      protected _separate_5_8_betChipStack: ro.BetChipStack;
      protected _separate_6_9_betChipStack: ro.BetChipStack;
      protected _separate_7_10_betChipStack: ro.BetChipStack;
      protected _separate_8_11_betChipStack: ro.BetChipStack;
      protected _separate_9_12_betChipStack: ro.BetChipStack;
      protected _separate_10_13_betChipStack: ro.BetChipStack;
      protected _separate_11_14_betChipStack: ro.BetChipStack;
      protected _separate_12_15_betChipStack: ro.BetChipStack;
      protected _separate_13_16_betChipStack: ro.BetChipStack;
      protected _separate_14_17_betChipStack: ro.BetChipStack;
      protected _separate_15_18_betChipStack: ro.BetChipStack;
      protected _separate_16_19_betChipStack: ro.BetChipStack;
      protected _separate_17_20_betChipStack: ro.BetChipStack;
      protected _separate_18_21_betChipStack: ro.BetChipStack;
      protected _separate_19_22_betChipStack: ro.BetChipStack;
      protected _separate_20_23_betChipStack: ro.BetChipStack;
      protected _separate_21_24_betChipStack: ro.BetChipStack;
      protected _separate_22_25_betChipStack: ro.BetChipStack;
      protected _separate_23_26_betChipStack: ro.BetChipStack;
      protected _separate_24_27_betChipStack: ro.BetChipStack;
      protected _separate_25_28_betChipStack: ro.BetChipStack;
      protected _separate_26_29_betChipStack: ro.BetChipStack;
      protected _separate_27_30_betChipStack: ro.BetChipStack;
      protected _separate_28_31_betChipStack: ro.BetChipStack;
      protected _separate_29_32_betChipStack: ro.BetChipStack;
      protected _separate_30_33_betChipStack: ro.BetChipStack;
      protected _separate_31_34_betChipStack: ro.BetChipStack;
      protected _separate_32_35_betChipStack: ro.BetChipStack;
      protected _separate_33_36_betChipStack: ro.BetChipStack;
      protected _street_1_2_3_betChipStack: ro.BetChipStack;
      protected _street_4_5_6_betChipStack: ro.BetChipStack;
      protected _street_7_8_9_betChipStack: ro.BetChipStack;
      protected _street_10_11_12_betChipStack: ro.BetChipStack;
      protected _street_13_14_15_betChipStack: ro.BetChipStack;
      protected _street_16_17_18_betChipStack: ro.BetChipStack;
      protected _street_19_20_21_betChipStack: ro.BetChipStack;
      protected _street_22_23_24_betChipStack: ro.BetChipStack;
      protected _street_25_26_27_betChipStack: ro.BetChipStack;
      protected _street_28_29_30_betChipStack: ro.BetChipStack;
      protected _street_31_32_33_betChipStack: ro.BetChipStack;
      protected _street_34_35_36_betChipStack: ro.BetChipStack;
      protected _street_0_1_2_betChipStack: ro.BetChipStack;
      protected _street_0_2_3_betChipStack: ro.BetChipStack;
      protected _corner_1_2_4_5_betChipStack: ro.BetChipStack;
      protected _corner_2_3_5_6_betChipStack: ro.BetChipStack;
      protected _corner_4_5_7_8_betChipStack: ro.BetChipStack;
      protected _corner_5_6_8_9_betChipStack: ro.BetChipStack;
      protected _corner_7_8_10_11_betChipStack: ro.BetChipStack;
      protected _corner_8_9_11_12_betChipStack: ro.BetChipStack;
      protected _corner_10_11_13_14_betChipStack: ro.BetChipStack;
      protected _corner_11_12_14_15_betChipStack: ro.BetChipStack;
      protected _corner_13_14_16_17_betChipStack: ro.BetChipStack;
      protected _corner_14_15_17_18_betChipStack: ro.BetChipStack;
      protected _corner_16_17_19_20_betChipStack: ro.BetChipStack;
      protected _corner_17_18_20_21_betChipStack: ro.BetChipStack;
      protected _corner_19_20_22_23_betChipStack: ro.BetChipStack;
      protected _corner_20_21_23_24_betChipStack: ro.BetChipStack;
      protected _corner_22_23_25_26_betChipStack: ro.BetChipStack;
      protected _corner_23_24_26_27_betChipStack: ro.BetChipStack;
      protected _corner_25_26_28_29_betChipStack: ro.BetChipStack;
      protected _corner_26_27_29_30_betChipStack: ro.BetChipStack;
      protected _corner_28_29_31_32_betChipStack: ro.BetChipStack;
      protected _corner_29_30_32_33_betChipStack: ro.BetChipStack;
      protected _corner_31_32_34_35_betChipStack: ro.BetChipStack;
      protected _corner_32_33_35_36_betChipStack: ro.BetChipStack;
      protected _corner_0_1_2_3_betChipStack: ro.BetChipStack;
      protected _line_1_6_betChipStack: ro.BetChipStack;
      protected _line_4_9_betChipStack: ro.BetChipStack;
      protected _line_7_12_betChipStack: ro.BetChipStack;
      protected _line_10_15_betChipStack: ro.BetChipStack;
      protected _line_13_18_betChipStack: ro.BetChipStack;
      protected _line_16_21_betChipStack: ro.BetChipStack;
      protected _line_19_24_betChipStack: ro.BetChipStack;
      protected _line_22_27_betChipStack: ro.BetChipStack;
      protected _line_25_30_betChipStack: ro.BetChipStack;
      protected _line_28_33_betChipStack: ro.BetChipStack;
      protected _line_31_36_betChipStack: ro.BetChipStack;
      protected _row_1_betChipStack: ro.BetChipStack;
      protected _row_2_betChipStack: ro.BetChipStack;
      protected _row_3_betChipStack: ro.BetChipStack;
      protected _dozen_1_12_betChipStack: ro.BetChipStack;
      protected _dozen_13_24_betChipStack: ro.BetChipStack;
      protected _dozen_25_36_betChipStack: ro.BetChipStack;
      protected _red_betChipStack: ro.BetChipStack;
      protected _black_betChipStack: ro.BetChipStack;
      protected _odd_betChipStack: ro.BetChipStack;
      protected _even_betChipStack: ro.BetChipStack;
      protected _small_betChipStack: ro.BetChipStack;
      protected _big_betChipStack: ro.BetChipStack;

      protected _groupHoverMapping: {};

      constructor() {
        super();
        this._betField = ro.BetField;
      }

      protected createMapping() {
        super.createMapping();
        this._mouseAreaMapping = {};
        this._mouseAreaMapping[ro.BetField.DIRECT_0] = this._direct_0_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_1] = this._direct_1_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_2] = this._direct_2_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_3] = this._direct_3_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_4] = this._direct_4_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_5] = this._direct_5_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_6] = this._direct_6_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_7] = this._direct_7_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_8] = this._direct_8_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_9] = this._direct_9_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_10] = this._direct_10_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_11] = this._direct_11_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_12] = this._direct_12_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_13] = this._direct_13_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_14] = this._direct_14_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_15] = this._direct_15_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_16] = this._direct_16_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_17] = this._direct_17_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_18] = this._direct_18_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_19] = this._direct_19_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_20] = this._direct_20_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_21] = this._direct_21_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_22] = this._direct_22_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_23] = this._direct_23_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_24] = this._direct_24_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_25] = this._direct_25_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_26] = this._direct_26_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_27] = this._direct_27_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_28] = this._direct_28_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_29] = this._direct_29_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_30] = this._direct_30_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_31] = this._direct_31_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_32] = this._direct_32_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_33] = this._direct_33_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_34] = this._direct_34_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_35] = this._direct_35_group;
        this._mouseAreaMapping[ro.BetField.DIRECT_36] = this._direct_36_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_1_2] = this._separate_1_2_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_2_3] = this._separate_2_3_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_4_5] = this._separate_4_5_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_5_6] = this._separate_5_6_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_7_8] = this._separate_7_8_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_8_9] = this._separate_8_9_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_10_11] = this._separate_10_11_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_11_12] = this._separate_11_12_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_13_14] = this._separate_13_14_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_14_15] = this._separate_14_15_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_16_17] = this._separate_16_17_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_17_18] = this._separate_17_18_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_19_20] = this._separate_19_20_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_20_21] = this._separate_20_21_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_22_23] = this._separate_22_23_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_23_24] = this._separate_23_24_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_25_26] = this._separate_25_26_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_26_27] = this._separate_26_27_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_28_29] = this._separate_28_29_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_29_30] = this._separate_29_30_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_31_32] = this._separate_31_32_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_32_33] = this._separate_32_33_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_34_35] = this._separate_34_35_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_35_36] = this._separate_35_36_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_0_1] = this._separate_0_1_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_0_2] = this._separate_0_2_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_0_3] = this._separate_0_3_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_1_4] = this._separate_1_4_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_2_5] = this._separate_2_5_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_3_6] = this._separate_3_6_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_4_7] = this._separate_4_7_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_5_8] = this._separate_5_8_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_6_9] = this._separate_6_9_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_7_10] = this._separate_7_10_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_8_11] = this._separate_8_11_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_9_12] = this._separate_9_12_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_10_13] = this._separate_10_13_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_11_14] = this._separate_11_14_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_12_15] = this._separate_12_15_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_13_16] = this._separate_13_16_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_14_17] = this._separate_14_17_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_15_18] = this._separate_15_18_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_16_19] = this._separate_16_19_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_17_20] = this._separate_17_20_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_18_21] = this._separate_18_21_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_19_22] = this._separate_19_22_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_20_23] = this._separate_20_23_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_21_24] = this._separate_21_24_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_22_25] = this._separate_22_25_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_23_26] = this._separate_23_26_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_24_27] = this._separate_24_27_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_25_28] = this._separate_25_28_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_26_29] = this._separate_26_29_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_27_30] = this._separate_27_30_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_28_31] = this._separate_28_31_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_29_32] = this._separate_29_32_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_30_33] = this._separate_30_33_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_31_34] = this._separate_31_34_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_32_35] = this._separate_32_35_group;
        this._mouseAreaMapping[ro.BetField.SEPARATE_33_36] = this._separate_33_36_group;
        this._mouseAreaMapping[ro.BetField.STREET_1_2_3] = this._street_1_2_3_group;
        this._mouseAreaMapping[ro.BetField.STREET_4_5_6] = this._street_4_5_6_group;
        this._mouseAreaMapping[ro.BetField.STREET_7_8_9] = this._street_7_8_9_group;
        this._mouseAreaMapping[ro.BetField.STREET_10_11_12] = this._street_10_11_12_group;
        this._mouseAreaMapping[ro.BetField.STREET_13_14_15] = this._street_13_14_15_group;
        this._mouseAreaMapping[ro.BetField.STREET_16_17_18] = this._street_16_17_18_group;
        this._mouseAreaMapping[ro.BetField.STREET_19_20_21] = this._street_19_20_21_group;
        this._mouseAreaMapping[ro.BetField.STREET_22_23_24] = this._street_22_23_24_group;
        this._mouseAreaMapping[ro.BetField.STREET_25_26_27] = this._street_25_26_27_group;
        this._mouseAreaMapping[ro.BetField.STREET_28_29_30] = this._street_28_29_30_group;
        this._mouseAreaMapping[ro.BetField.STREET_31_32_33] = this._street_31_32_33_group;
        this._mouseAreaMapping[ro.BetField.STREET_34_35_36] = this._street_34_35_36_group;
        this._mouseAreaMapping[ro.BetField.STREET_0_1_2] = this._street_0_1_2_group;
        this._mouseAreaMapping[ro.BetField.STREET_0_2_3] = this._street_0_2_3_group;
        this._mouseAreaMapping[ro.BetField.CORNER_1_2_4_5] = this._corner_1_2_4_5_group;
        this._mouseAreaMapping[ro.BetField.CORNER_2_3_5_6] = this._corner_2_3_5_6_group;
        this._mouseAreaMapping[ro.BetField.CORNER_4_5_7_8] = this._corner_4_5_7_8_group;
        this._mouseAreaMapping[ro.BetField.CORNER_5_6_8_9] = this._corner_5_6_8_9_group;
        this._mouseAreaMapping[ro.BetField.CORNER_7_8_10_11] = this._corner_7_8_10_11_group;
        this._mouseAreaMapping[ro.BetField.CORNER_8_9_11_12] = this._corner_8_9_11_12_group;
        this._mouseAreaMapping[ro.BetField.CORNER_10_11_13_14] = this._corner_10_11_13_14_group;
        this._mouseAreaMapping[ro.BetField.CORNER_11_12_14_15] = this._corner_11_12_14_15_group;
        this._mouseAreaMapping[ro.BetField.CORNER_13_14_16_17] = this._corner_13_14_16_17_group;
        this._mouseAreaMapping[ro.BetField.CORNER_14_15_17_18] = this._corner_14_15_17_18_group;
        this._mouseAreaMapping[ro.BetField.CORNER_16_17_19_20] = this._corner_16_17_19_20_group;
        this._mouseAreaMapping[ro.BetField.CORNER_17_18_20_21] = this._corner_17_18_20_21_group;
        this._mouseAreaMapping[ro.BetField.CORNER_19_20_22_23] = this._corner_19_20_22_23_group;
        this._mouseAreaMapping[ro.BetField.CORNER_20_21_23_24] = this._corner_20_21_23_24_group;
        this._mouseAreaMapping[ro.BetField.CORNER_22_23_25_26] = this._corner_22_23_25_26_group;
        this._mouseAreaMapping[ro.BetField.CORNER_23_24_26_27] = this._corner_23_24_26_27_group;
        this._mouseAreaMapping[ro.BetField.CORNER_25_26_28_29] = this._corner_25_26_28_29_group;
        this._mouseAreaMapping[ro.BetField.CORNER_26_27_29_30] = this._corner_26_27_29_30_group;
        this._mouseAreaMapping[ro.BetField.CORNER_28_29_31_32] = this._corner_28_29_31_32_group;
        this._mouseAreaMapping[ro.BetField.CORNER_29_30_32_33] = this._corner_29_30_32_33_group;
        this._mouseAreaMapping[ro.BetField.CORNER_31_32_34_35] = this._corner_31_32_34_35_group;
        this._mouseAreaMapping[ro.BetField.CORNER_32_33_35_36] = this._corner_32_33_35_36_group;
        this._mouseAreaMapping[ro.BetField.CORNER_0_1_2_3] = this._corner_0_1_2_3_group;
        this._mouseAreaMapping[ro.BetField.LINE_1_6] = this._line_1_6_group;
        this._mouseAreaMapping[ro.BetField.LINE_4_9] = this._line_4_9_group;
        this._mouseAreaMapping[ro.BetField.LINE_7_12] = this._line_7_12_group;
        this._mouseAreaMapping[ro.BetField.LINE_10_15] = this._line_10_15_group;
        this._mouseAreaMapping[ro.BetField.LINE_13_18] = this._line_13_18_group;
        this._mouseAreaMapping[ro.BetField.LINE_16_21] = this._line_16_21_group;
        this._mouseAreaMapping[ro.BetField.LINE_19_24] = this._line_19_24_group;
        this._mouseAreaMapping[ro.BetField.LINE_22_27] = this._line_22_27_group;
        this._mouseAreaMapping[ro.BetField.LINE_25_30] = this._line_25_30_group;
        this._mouseAreaMapping[ro.BetField.LINE_28_33] = this._line_28_33_group;
        this._mouseAreaMapping[ro.BetField.LINE_31_36] = this._line_31_36_group;
        this._mouseAreaMapping[ro.BetField.ROW_1] = this._row_1_group;
        this._mouseAreaMapping[ro.BetField.ROW_2] = this._row_2_group;
        this._mouseAreaMapping[ro.BetField.ROW_3] = this._row_3_group;
        this._mouseAreaMapping[ro.BetField.DOZEN_1_12] = this._dozen_1_12_group;
        this._mouseAreaMapping[ro.BetField.DOZEN_13_24] = this._dozen_13_24_group;
        this._mouseAreaMapping[ro.BetField.DOZEN_25_36] = this._dozen_25_36_group;
        this._mouseAreaMapping[ro.BetField.RED] = this._red_group;
        this._mouseAreaMapping[ro.BetField.BLACK] = this._black_group;
        this._mouseAreaMapping[ro.BetField.ODD] = this._odd_group;
        this._mouseAreaMapping[ro.BetField.EVEN] = this._even_group;
        this._mouseAreaMapping[ro.BetField.SMALL] = this._small_group;
        this._mouseAreaMapping[ro.BetField.BIG] = this._big_group;

        Object.keys(this._mouseAreaMapping).map(value => {
          mouse.setButtonMode(this._mouseAreaMapping[value], true);
        });

        this._betChipStackMapping = {};
        this._betChipStackMapping[ro.BetField.DIRECT_0] = this._direct_0_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_1] = this._direct_1_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_2] = this._direct_2_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_3] = this._direct_3_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_3] = this._direct_3_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_4] = this._direct_4_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_5] = this._direct_5_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_6] = this._direct_6_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_7] = this._direct_7_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_8] = this._direct_8_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_9] = this._direct_9_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_10] = this._direct_10_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_11] = this._direct_11_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_12] = this._direct_12_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_13] = this._direct_13_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_14] = this._direct_14_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_15] = this._direct_15_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_16] = this._direct_16_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_17] = this._direct_17_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_18] = this._direct_18_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_19] = this._direct_19_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_20] = this._direct_20_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_21] = this._direct_21_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_22] = this._direct_22_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_23] = this._direct_23_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_24] = this._direct_24_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_25] = this._direct_25_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_26] = this._direct_26_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_27] = this._direct_27_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_28] = this._direct_28_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_29] = this._direct_29_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_30] = this._direct_30_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_31] = this._direct_31_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_32] = this._direct_32_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_33] = this._direct_33_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_34] = this._direct_34_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_35] = this._direct_35_betChipStack;
        this._betChipStackMapping[ro.BetField.DIRECT_36] = this._direct_36_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_1_2] = this._separate_1_2_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_2_3] = this._separate_2_3_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_4_5] = this._separate_4_5_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_5_6] = this._separate_5_6_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_7_8] = this._separate_7_8_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_8_9] = this._separate_8_9_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_10_11] = this._separate_10_11_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_11_12] = this._separate_11_12_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_13_14] = this._separate_13_14_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_14_15] = this._separate_14_15_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_16_17] = this._separate_16_17_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_17_18] = this._separate_17_18_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_19_20] = this._separate_19_20_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_20_21] = this._separate_20_21_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_22_23] = this._separate_22_23_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_23_24] = this._separate_23_24_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_25_26] = this._separate_25_26_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_26_27] = this._separate_26_27_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_28_29] = this._separate_28_29_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_29_30] = this._separate_29_30_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_31_32] = this._separate_31_32_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_32_33] = this._separate_32_33_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_34_35] = this._separate_34_35_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_35_36] = this._separate_35_36_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_0_1] = this._separate_0_1_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_0_2] = this._separate_0_2_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_0_3] = this._separate_0_3_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_1_4] = this._separate_1_4_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_2_5] = this._separate_2_5_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_3_6] = this._separate_3_6_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_4_7] = this._separate_4_7_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_5_8] = this._separate_5_8_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_6_9] = this._separate_6_9_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_7_10] = this._separate_7_10_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_8_11] = this._separate_8_11_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_9_12] = this._separate_9_12_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_10_13] = this._separate_10_13_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_11_14] = this._separate_11_14_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_12_15] = this._separate_12_15_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_13_16] = this._separate_13_16_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_14_17] = this._separate_14_17_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_15_18] = this._separate_15_18_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_16_19] = this._separate_16_19_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_17_20] = this._separate_17_20_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_18_21] = this._separate_18_21_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_19_22] = this._separate_19_22_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_20_23] = this._separate_20_23_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_21_24] = this._separate_21_24_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_22_25] = this._separate_22_25_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_23_26] = this._separate_23_26_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_24_27] = this._separate_24_27_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_25_28] = this._separate_25_28_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_26_29] = this._separate_26_29_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_27_30] = this._separate_27_30_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_28_31] = this._separate_28_31_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_29_32] = this._separate_29_32_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_30_33] = this._separate_30_33_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_31_34] = this._separate_31_34_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_32_35] = this._separate_32_35_betChipStack;
        this._betChipStackMapping[ro.BetField.SEPARATE_33_36] = this._separate_33_36_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_1_2_3] = this._street_1_2_3_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_4_5_6] = this._street_4_5_6_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_7_8_9] = this._street_7_8_9_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_10_11_12] = this._street_10_11_12_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_13_14_15] = this._street_13_14_15_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_16_17_18] = this._street_16_17_18_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_19_20_21] = this._street_19_20_21_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_22_23_24] = this._street_22_23_24_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_25_26_27] = this._street_25_26_27_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_28_29_30] = this._street_28_29_30_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_31_32_33] = this._street_31_32_33_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_34_35_36] = this._street_34_35_36_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_0_1_2] = this._street_0_1_2_betChipStack;
        this._betChipStackMapping[ro.BetField.STREET_0_2_3] = this._street_0_2_3_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_1_2_4_5] = this._corner_1_2_4_5_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_2_3_5_6] = this._corner_2_3_5_6_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_4_5_7_8] = this._corner_4_5_7_8_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_5_6_8_9] = this._corner_5_6_8_9_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_7_8_10_11] = this._corner_7_8_10_11_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_8_9_11_12] = this._corner_8_9_11_12_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_10_11_13_14] = this._corner_10_11_13_14_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_11_12_14_15] = this._corner_11_12_14_15_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_13_14_16_17] = this._corner_13_14_16_17_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_14_15_17_18] = this._corner_14_15_17_18_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_16_17_19_20] = this._corner_16_17_19_20_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_17_18_20_21] = this._corner_17_18_20_21_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_19_20_22_23] = this._corner_19_20_22_23_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_20_21_23_24] = this._corner_20_21_23_24_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_22_23_25_26] = this._corner_22_23_25_26_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_23_24_26_27] = this._corner_23_24_26_27_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_25_26_28_29] = this._corner_25_26_28_29_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_26_27_29_30] = this._corner_26_27_29_30_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_28_29_31_32] = this._corner_28_29_31_32_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_29_30_32_33] = this._corner_29_30_32_33_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_31_32_34_35] = this._corner_31_32_34_35_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_32_33_35_36] = this._corner_32_33_35_36_betChipStack;
        this._betChipStackMapping[ro.BetField.CORNER_0_1_2_3] = this._corner_0_1_2_3_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_1_6] = this._line_1_6_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_4_9] = this._line_4_9_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_7_12] = this._line_7_12_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_10_15] = this._line_10_15_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_13_18] = this._line_13_18_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_16_21] = this._line_16_21_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_19_24] = this._line_19_24_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_22_27] = this._line_22_27_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_25_30] = this._line_25_30_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_28_33] = this._line_28_33_betChipStack;
        this._betChipStackMapping[ro.BetField.LINE_31_36] = this._line_31_36_betChipStack;
        this._betChipStackMapping[ro.BetField.ROW_1] = this._row_1_betChipStack;
        this._betChipStackMapping[ro.BetField.ROW_2] = this._row_2_betChipStack;
        this._betChipStackMapping[ro.BetField.ROW_3] = this._row_3_betChipStack;
        this._betChipStackMapping[ro.BetField.DOZEN_1_12] = this._dozen_1_12_betChipStack;
        this._betChipStackMapping[ro.BetField.DOZEN_13_24] = this._dozen_13_24_betChipStack;
        this._betChipStackMapping[ro.BetField.DOZEN_25_36] = this._dozen_25_36_betChipStack;
        this._betChipStackMapping[ro.BetField.RED] = this._red_betChipStack;
        this._betChipStackMapping[ro.BetField.BLACK] = this._black_betChipStack;
        this._betChipStackMapping[ro.BetField.ODD] = this._odd_betChipStack;
        this._betChipStackMapping[ro.BetField.EVEN] = this._even_betChipStack;
        this._betChipStackMapping[ro.BetField.SMALL] = this._small_betChipStack;
        this._betChipStackMapping[ro.BetField.BIG] = this._big_betChipStack;

        this._groupHoverMapping = {};
        Object.keys(we.ro.BETFIELD_MAPPING).map(value => {
          this._groupHoverMapping[value] = we.ro.BETFIELD_MAPPING[value];
        });
      }

      protected isExceedLowerBetLimit(fieldAmounts: {}, betLimit: data.BetLimitSet) {
        for (const key of Object.keys(fieldAmounts)) {
          if (fieldAmounts[key] === 0) {
            continue;
          }
          if (fieldAmounts[key] < betLimit.minlimit) {
            return true;
          }
        }
        return false;
      }
      protected isExceedUpperBetLimit(fieldAmounts: {}, betLimit: data.BetLimitSet, betDetail: data.BetDetail) {
        for (const key of Object.keys(fieldAmounts)) {
          if (fieldAmounts[key] === 0) {
            continue;
          }
          if (fieldAmounts[key] > betLimit.maxlimit) {
            return 'upper';
          }
          if (fieldAmounts[key] < betLimit.minlimit) {
            return 'lower';
          }
        }
        return null;
      }

      public onGridRollover(fieldName: string) {
        this._groupHoverMapping[fieldName].map(value => this._tableLayer.onRollover(value));
      }

      public onGridRollout(fieldName: string) {
        this._groupHoverMapping[fieldName].map(value => this._tableLayer.onRollout(value));
      }

      public onBetFieldUpdate(fieldNames: string[], hashkey: string = null) {
        super.onBetFieldUpdate(fieldNames, hashkey);
        dir.evtHandler.dispatch(we.core.Event.BET_COMBINATION_AMOUNT_UPDATE, {
          amount: this.getTotalCfmBetAmount() + this.getTotalUncfmBetAmount(),
        });
      }

      protected undoBetFieldUpdate(data: { field: string; amount: number }) {
        super.undoBetFieldUpdate(data);
        dir.evtHandler.dispatch(we.core.Event.BET_COMBINATION_AMOUNT_UPDATE, { amount: this.getTotalCfmBetAmount() + this.getTotalUncfmBetAmount() });
      }

      public onDoublePressed() {
        super.onDoublePressed();
        dir.evtHandler.dispatch(we.core.Event.BET_COMBINATION_AMOUNT_UPDATE, { amount: this.getTotalCfmBetAmount() + this.getTotalUncfmBetAmount() });
      }
      public undoDoubleBetFields(betDetails: data.BetDetail[]) {
        super.undoDoubleBetFields(betDetails);
        dir.evtHandler.dispatch(we.core.Event.BET_COMBINATION_AMOUNT_UPDATE, { amount: this.getTotalCfmBetAmount() + this.getTotalUncfmBetAmount() });
      }
      public onRepeatPressed() {
        super.onRepeatPressed();
        dir.evtHandler.dispatch(we.core.Event.BET_COMBINATION_AMOUNT_UPDATE, { amount: this.getTotalCfmBetAmount() + this.getTotalUncfmBetAmount() });
      }
      protected undoRepeatBetFields(betDetails: data.BetDetail[]) {
        super.undoRepeatBetFields(betDetails);
        dir.evtHandler.dispatch(we.core.Event.BET_COMBINATION_AMOUNT_UPDATE, { amount: this.getTotalCfmBetAmount() + this.getTotalUncfmBetAmount() });
      }
    }
  }
}
